### ISSUE TITLE
Progress not being registered

### ISSUE THREAD

**Issue by databaseadmins** [rmotr-curriculum/post-your-question-questions#1]
It looks like progress on my lessons isn't being registered.  For example, I finished the passwords lesson but it still has a cleared out o instead of the nice blue one indicating completion.

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by martinzugnoni** [comment]
I'll take a look, Burt. Thanks for pointing it out.

**Comment by martinzugnoni** [comment]
Hi Burt, it should be fixed by now. If you notice similar problems again, please let us know ASAP. We are chasing a possible bug, that we think is resolved, but it might not be.
