### ISSUE TITLE
Strings immutable and variable re-assignment

### ISSUE THREAD

**Issue by cmoore1** [rmotr-curriculum/post-your-question-questions#100]
This is more of a theoretical question. I understand that strings are immutable and that are effectively lost if re-assigned without a pointer in memory. However, is there a gap in time where the the original could be referenced by Python before being cleaned out of memory. In the first string video of the 2nd part of class you showed that if you put something like msg = 'Hello' ; alt_msg = msg ; msg = msg.lower() then you would have both references. All of this is to ask is there a cleanup period that could occur in corner cases where floating references could be called in code because of recycled variable names in a program? 

Sorry I know this is a bit of a stretch my mind just works like this at times.

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
msg = 'Hello'
alt_msg = msg

msg = msg.lower()

*************************************

#Now msg effectively points to 'hello' and alt_msg points to 'Hello'
```

**Comment by jsymons** [comment]
This would only be an issue when dealing with threading which is a topic we haven't covered yet. We would normally refer to this as a concurrency issue. However in this particular case `msg` is 'Hello' up until the point that `msg = msg.lower` is executed. What happens there is it goes take the current value of `msg` and call `lower()` on it, then give me the result of that and assign it to `msg`. The original is intact until that assignment operation happens, in which case it becomes replaced.
