### ISSUE TITLE
Hangman OOP Project

### ISSUE THREAD

**Issue by skimtephen** [rmotr-curriculum/post-your-question-questions#101]
Hi, I'm having a little bit of trouble running this test in the 2nd Hangman project. Not exactly sure how we are supposed to incorporate GuessAttempt and Perform_Attempt. Santiago in the Slack Channel mentioned that we would need return GuessAttempt in Perform_Attempt, but not exactly sure what he is saying

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
def test_guess_word_with_miss_character():
    word = GuessWord('Python')
    attempt = word.perform_attempt('z')

    assert attempt.is_miss() is True
    assert attempt.is_hit() is False

    assert word.masked == '******'
```

**Comment by jsymons** [comment]
So basically `GuessAttempt` Is a 'dumb class' it's just a data structure with no real logic involved. When we execute `GuessWord`'s `perform_attempt` method the tests expect that `perform_attempt` returns an instance of the `GuessAttempt` class (that's where the `is_hit` and `is_miss` methods are coming from). If you need further clarification feel free to re-open this.
