### ISSUE TITLE
class Meta behavior question

### ISSUE THREAD

**Issue by CipherSanctum** [rmotr-curriculum/post-your-question-questions#102]
Hi, on the rmotrgram project, can you please explain the class Meta for me?? I've been playing around with it, found out I have access to User attributes, and I'd like to know:

Why doesn't the User object on line 32 throw an error when the UserFactory is created???
Afterall, there is no email parameter given in that. But the UserFactory acts as if the variables in it are being passed into the __init__ of the User class.

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
import factory


class User(object):
    def __init__(self, first_name, last_name, email):
        self.first_name = first_name
        self.last_name = last_name
        self.email = email
        self.posts = []
        self.following = []

    def add_post(self, post):
        pass

    def get_timeline(self):
        pass

    def follow(self, other):
        pass


class UserFactory(factory.Factory):
    class Meta:
        model = User  # I know this class Meta gives UserFactory access to User attributes/methods

    first_name = factory.Iterator(['Kevin', 'Joe', 'Ervin', 'Daniel'])
    last_name = factory.Iterator(['Watson', 'Fowler', 'Roberts', 'Wiley'])
    email = factory.LazyAttribute(lambda u: '{}.{}@fake-domain.com'.format(
        u.first_name, u.last_name))


user = UserFactory(first_name='Kevin', last_name='Watson')
print(user.email)
print(user.posts)



```

**Comment by jsymons** [comment]
So this is going to sidetrack a little off the project... `factory` is provided by the Factory Boy package (https://factoryboy.readthedocs.io/en/latest/) which is for generating objects for testing, we're not expecting you to use `factory` in your project, we're just using it as part of the tests. To really understand how Factory Boy works you'll have to look at the documentation linked. Basically it works as a fixture replacement meant to allow you to generate objects while only declaring the fields required for your tests.
