### ISSUE TITLE
Football Dictionaries Assignment 1

### ISSUE THREAD

**Issue by F0R6E** [rmotr-curriculum/post-your-question-questions#106]
I'm not sure why this isn't working. It fills in everything just fine on the first pass through of the loop, but then on the second pass it overwrites it. 

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
def players_as_dictionaries(squads_list):
    players_list = []
    players_dict = {
        'Number' : '',
        'Position' : '',
        'Name' : '',
        'Date of Birth' : '',
        'Caps' : '',
        'Club' : '',
        'Country (Players Country)' : '',
        'Club Country' : '',
        'Year' : ''
        }
    for item in squads_list:
        players_dict['Number'] = item[0]
        players_dict['Position'] = item[1]
        players_dict['Name'] = item[2]
        players_dict['Date of Birth'] = item[3]
        players_dict['Caps'] = item[4]
        players_dict['Club'] = item[5]
        players_dict['Country (Players Country)'] = item[6]
        players_dict['Club Country'] = item[7]
        players_dict['Year'] = item[8]
	players_list.append(players_dict)
        
        
    print(players_dict)
```

**Comment by jsymons** [comment]
You need to put the definition of your dictionary inside your for loop. By having it outside the loop you end up using the **same** dictionary each iteration, so whenever you change the values in it the values are changed for all the references to it in your list. By defining it inside the loop you use a new dictionary each iteration.

**Comment by zonagilreath** [comment]
I think the more pressing issue is that `players_dict` is being printed at the end. `players_dict` will contain the values from the latest loop no matter whether it's defined initially inside or before the loop, if you want all of the player dicts you've created, you need to return or print the list that you've been appending them to.
