### ISSUE TITLE
How else would you send HTTP requests if you didn't have access to the "requests" library?  How difficult is this otherwise?

### ISSUE THREAD

**Issue by gitdownagain** [rmotr-curriculum/post-your-question-questions#107]
Just trying to understand requests better and understand what the advantages are of the requests library.

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python

```

**Comment by jsymons** [comment]
You would end up having to use the `urllib.request` module, which is part of the standard library. However using the requests package is do ubiquitous that even the documentation for `urllib.request` recommends using the requests package: https://docs.python.org/3.5/library/urllib.request.html#module-urllib.request
