### ISSUE TITLE
Data Science Program questions

### ISSUE THREAD

**Issue by mizjane07** [rmotr-curriculum/post-your-question-questions#109]
I had some general questions about the course.  I tuned in for the first class last night and I am feeling a little overwhelmed.  I joined on Thursday last week and had some technical issues with my computer over the weekend.  I didn't get through a lot of the prrep material.  What is the best way to start now.  Should I go through the cards previous to the last night's class and then move forward until I have time to go through the prep material later in the week.

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by martinzugnoni** [comment]
Hello! Don't worry. It happens a lot that there're a lot of new concepts to digest during the first week. Try to do your best spending time practicing and reading the material in the platform. Also join the daily mentor sessions at night, so you can evacuate any questions that appear along the way. The weekend is also a good buffer for you to catch up with all the pending tasks from the week.
Please let us know if we can help you somehow. ;-)
