### ISSUE TITLE
Unit 5, Baking Cookies exercise returning "Server Error (500)"

### ISSUE THREAD

**Issue by useraddmario** [rmotr-curriculum/post-your-question-questions#11]
Unit 5, Baking Cookies exercise returning "Server Error (500)" instead of problem.

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by jasonmeeks** [comment]
@useraddmario is this still happening for you? the link works for me.

**Comment by santiagobasulto** [comment]
Yes, I fixed it earlier today. Should be working.

**Comment by useraddmario** [comment]
It's good now, thanks.

Mario
