### ISSUE TITLE
Github pull request for hangman game Week 4 Project

### ISSUE THREAD

**Issue by cmoore1** [rmotr-curriculum/post-your-question-questions#111]
Hello, I have a pull request on github showing passing all tests and has been verified. However, I am having issues getting my RMOTR page to update.

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by santiagobasulto** [comment]
hey Chris! Can you ping me on Slack with details about the project and the pull request link?
