### ISSUE TITLE
Class 12 Inheritence Lecture?

### ISSUE THREAD

**Issue by cmoore1** [rmotr-curriculum/post-your-question-questions#113]
Hello when I try to watch the recording of the Class 12 Inheritence Lecture it is only 17 seconds long? Is there somewhere I can view this?

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by santiagobasulto** [comment]
Chris, there's obviously something wrong. I'll check what's going on and get back to you shortly.

**Comment by santiagobasulto** [comment]
Chris, something went wrong with the previous recording. I temporarily posted the one from our previous batch while I check with Andrew. If you have questions about it post them on the channel, I'm online.

**Comment by SoniaBuckley** [comment]
I am also having trouble with this.  Can you please re-post the one from previous batch @santiagobasulto ?  Thanks!

**Comment by santiagobasulto** [comment]
Oh, my bad Sonia! I forgot to update it, sorry. It's updated now, and here's the link just in case: https://www.youtube.com/watch?v=kestRfyiKmk
