### ISSUE TITLE
Can someone explain the portions of this button on the Ecommerce ModelForm project?

### ISSUE THREAD

**Issue by gitdownagain** [rmotr-curriculum/post-your-question-questions#115]
Just trying to understand what the CLASS text is doing in these two buttons.  And why does the delete portion have two href tags?

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
<a href="/edit-product/{{product.id}}"><button class="btn btn-info btn-xs fas fa-edit" title="Edit"></button></a>

<a href="/delete-product/{{product.id}}"><button class="btn btn-danger btn-xs fas fa-trash" href="/delete-product/{{product.id}}" title="Delete"></button></a>

```

**Comment by jsymons** [comment]
The class part of the tag is responsible for assigning CSS classes, these in particular are from [Bootstrap](https://getbootstrap.com/). As for the second button it's not actually doing anything as href isn't a valid button attribute and is thus ignored.
