### ISSUE TITLE
Week 7 File Management

### ISSUE THREAD

**Issue by cmoore1** [rmotr-curriculum/post-your-question-questions#117]
Hello, I fell behind and am trying to catch up with the class. I am going through Week 7 on File Management. I just noted that I do not see a project after the second lecture recording? Is this intentional? Are there time limits to access the project?

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by santiagobasulto** [comment]
Hello @cmoore1! Yes, the platform is the main source of truth. There's no project that week, BUT, there's "homework" that is the continuation of the class activity. You can see it under [student's resources for class 7](https://docs.google.com/document/d/1aah_fj5GpamS2sd7VqA0fa-0DfUfnIj7hLW-58t-vME/edit).
