### ISSUE TITLE
Django Basic Views Practice: Profile view Error

### ISSUE THREAD

**Issue by outdoorblake** [rmotr-curriculum/post-your-question-questions#118]
Hello,

I am getting an error for the Profile view in the following project:
https://github.com/blakepeeling/wdc-django-basic-views

The error I am getting is the following:
-------------------------------------
ValueError at /authors/
The view django_basic_views.views.authors didn't return an HttpResponse object. It returned None instead.

Traceback from Error:
Environment:
Request Method: GET
Request URL: http://e5a5e32ef2774df3addcb3b15dcd5f00.vfs.cloud9.us-west-2.amazonaws.com/authors/

Django Version: 2.1.2
Python Version: 3.6.7
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback:

File "/home/ec2-user/environment/wdc-django-basic-views/django_basic_views/local/lib/python3.6/dist-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/home/ec2-user/environment/wdc-django-basic-views/django_basic_views/local/lib/python3.6/dist-packages/django/core/handlers/base.py" in _get_response
  137.                 "returned None instead." % (callback.__module__, view_name)

Exception Type: ValueError at /authors/
Exception Value: The view django_basic_views.views.authors didn't return an HttpResponse object. It returned None instead.

-----------------------------------

I tried doing some Googling of it and this error seems to be related to not returning an HttpReponse or render(). But I can't see where I am going wrong in my code. Any help would be appreciated!

Thanks,
Blake

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
#my code in views.py file
# Use /profile URL
def profile(request):
    """
        This view should render the template 'profile.html'. Make sure you return
        the correct context to make it work.
    """
    return render(request, 'profile.html', {'my_name':'Blake', 'my_age':'23'})
    
    
#my code in urls.py file
urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello-world/', views.hello_world, name='hello_world'),
    path('date/', views.current_date, name='date'),
    path('my-age/<str:year>/<str:month>/<str:day>/', views.my_age, name='my_age'),
    path('next-birthday/<birthday>/', views.next_birthday, name='next_birthday'),
    path('profile/', views.profile, name='profile'),
    path('authors/', views.authors, name='authors'),
    path('author/<str:authors_last_name>', views.author, name='author'),
]




```

**Comment by santiagobasulto** [comment]
Hey Blake! This is a pretty common error, with time you'll learn how to interpret them. It's part of immersing yourself in the Django universe. The issue right there is that the view serving `authors/` (probably `views.authors`) is not returning a response.

The request URL seems to be `http://e5a5e32ef2774df3addcb3b15dcd5f00.vfs.cloud9.us-west-2.amazonaws.com/authors/` (from your error above). Try using `/profile` instead, that is the one you had in your views file.

I'll leave the issue open, let us know how it goes.

**Comment by outdoorblake** [comment]
Yikes...thats a major brainfart on my end. lol, thanks Santiago!
