### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by carl78050** [rmotr-curriculum/post-your-question-questions#119]
For some reason I can't figure out the palindromic primes quiz. Is there a way to get help?

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by martinzugnoni** [comment]
Hi @carl78050, sure! can you post the link to the assignment so I can take a look? thanks.

**Comment by carl78050** [comment]
https://learn.rmotr.com/python/base-python-track/intro-to-control-flow/palindromic-primes

**Comment by carl78050** [comment]
I'm basically don't know how to start

**Comment by martinzugnoni** [comment]
Well, it's just a matter of looping through numbers until the first one returns True in both `is_palindromic()` and `is_prime()` functions. The true logic is implemented inside those functions.

**Comment by santiagobasulto** [comment]
Hey @carl78050! That's one of the most difficult assignments in the unit, so congrats on the progress so far :)

The key here is "divide and conquer". Take a stab at each function. Can you solve `is_prime` first?

**Comment by carl78050** [comment]
Not really. I'm very much stuck here

**Comment by jsymons** [comment]
The easy one to tackle first is `is_palindrome` as you just need to check if the reverse of the number still equals the number. From there for the prime number bit take a look at my response to https://github.com/rmotr-curriculum/base-python-curriculum-questions/issues/368
