### ISSUE TITLE
Strip method

### ISSUE THREAD

**Issue by selmabensaid** [rmotr-curriculum/post-your-question-questions#122]
I am trying to use the strip method to remove space and new line but I'm not getting the expected result:
testing_recipients = """
Jon Snow <jon@starks.com>,
arya@starks.com   ,
Eddard "Ned" Stark <ned@starks.com>,
sansa@starks.com,
jon@starks.com,
   Arya No Face <arya@starks.com>
"""
clean_recipients=testing_recipients.strip()

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by jsymons** [comment]
As per [the Python documentation](https://docs.python.org/2/library/string.html#string.strip) `strip` removes leading and trailing whitespace, so in this example it would remove the newline before "Jon Snow jon@starks.com," and the newline after "Arya No Face arya@starks.com".
