### ISSUE TITLE
group_users_by_email_domain exercise

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/post-your-question-questions#123]
Hi Jason, I am doing warm up activity group user by email domain(Advanced collections) and have couple of questions:

1. Can you please let me know what this code does in the solution ?

users_dict.setdefault(domain, [])
why can't I just have this line 
users_dict[domain].append(user) instead of set default?

2.
If an user doesn't have a domain name in email address(say typo), then how do I solve this?
For instance the below didn't work for me. Got substring not found error

_def group_users_by_email_domain(multiple_users):
    users_dict = {}
    for user in multiple_users:
        if user['email'].index('@')==False:
            users_dict.setdefault(email,[])
            users_dict['No domain'].append(user)
        elif user['email'].index('@')==True:
            domain = user['email'].split('@')[1]
            users_dict.setdefault(domain,[])
            users_dict[domain].append(user)
         
    return users_dict_

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by jsymons** [comment]
If the key `domain` doesn't currently exist in `users_dict` you'll get a `KeyError`, the `setdefault` prevents this. Quick explanation of what `setdefault` does:
```python
users_dict.setdefault(domain, [])
```
is functionally the same as:
```python
if domain not in users_dict.keys():
    users_dict[keys] = []
```
So if we call `my_dict.setdefault(my_key, default_value)` it checks to see if `my_key` exists in `my_dict`, if it does it doesn't do anything, however if it doesn't it creates it and sets the associated value to `default_value`.
