### ISSUE TITLE
strip method

### ISSUE THREAD

**Issue by selmabensaid** [rmotr-curriculum/post-your-question-questions#124]
I am trying to use the strip() method to remove white spaces and new lines but it is not working. 
Am I doing something wrong?

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
testing_recipients = """
Jon Snow <jon@starks.com>,
arya@starks.com   ,
Eddard "Ned" Stark <ned@starks.com>,
sansa@starks.com,
jon@starks.com,
   Arya No Face <arya@starks.com>
"""
testing_recipients.strip(" ")
print (testing_recipients)
testing_recipients.strip()
print (testing_recipients)
# your code here (if any)
```

**Comment by jsymons** [comment]
Strip can't do in place replacement since in Python strings are immutable. As a result of that strip instead returns a new string with the whitespace removed, so you need to store is return value into a variable.
