### ISSUE TITLE
The order of adding to variable s

### ISSUE THREAD

**Issue by moose241986** [rmotr-curriculum/post-your-question-questions#125]
Going through the conditional statements the code evolves  to a finally end at "p*t**n". Why doesn't this code end up this way  "pn" + "ptn" + "*" = pnptn*

"""
pn
ptn
p*t**n

"""

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
word = 'python'
#mask = len(word)* "*"
mask = "p****n"
letter = "t"
s = ""

for i in range(len(word)):
  word_letter = word[i]
  mask_letter = mask[i]
  #print(word_letter,mask_letter)
  
  if mask_letter != "*":
    s += mask_letter
  

  
  elif letter == word_letter:
    s += word_letter
  
  else:
    s += "*"
  
  #print(word_letter,mask_letter)
print(s)
```

**Comment by ghost** [comment]
Please ignore this question. I figured it out. I didn't go step by step with the index i. I didn't realize the for loop and each letter from mask_letter and word_letter goes through the conditional statements before it goes through the for loop to the next iteration variable.
