### ISSUE TITLE
posts.py (test_post_string_representation())

### ISSUE THREAD

**Issue by rlrogers** [rmotr-curriculum/post-your-question-questions#13]
Hello,

I am working on the third and final test for posts.py file: test_post_string_representation.  

I am doing by best to format the returning string, but I am having issues with formatting the first_name and the last_name. I am trying to use the super() method to stay dry.  

Would you please steer me in the right direction? 

Thank you,
Richard

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
from datetime import datetime


class Post(object):
    def __init__(self, text, timestamp=None, first_name, last_name):
        self.text = text
        self.timestamp = timestamp
        self.user = None
        self.first_name = first_name
        self.last_name = last_name

    def set_user(self, user):
        self.user = user

class TextPost(Post):  # Inherit properly
    def __init__(self, text, timestamp=None):
        super(TextPost, self).__init__(text, timestamp, first_name, last_name)
        
    def __str__(self):
         return '@{}: "{}"\n\t{}'.format(self.first_name, self.last_name, self.text, self.timestamp('%A, %b %d, %Y'))


class PicturePost(Post):  # Inherit properly
    def __init__(self, text, image_url, timestamp=None):
        super(PicturePost, self).__init__(text, timestamp, first_name, last_name)
        self.image_url = image_url

    def __str__(self):
        return '@{}: "{}"\n\t{}\n\t{}'.format(self.first_name, self.text, self.image_url, self.timestamp('%A, %b %d, %Y'))


class CheckInPost(Post):  # Inherit properly
    def __init__(self, text, latitude, longitude, timestamp=None):
        super(CheckInPost, self).__init__(text, timestamp, first_name, last_name)
        self.latitude = latitude
        self.longitude = longitude
        
    def __str__(self):
        return '@{} {}: "{}"\n\t{}\n\t{}'.format(self.first_name, self.last_name, self.text, self.latitude, self.longitude, self.timestamp('%A, %b %d, %Y'))

```

**Comment by jsymons** [comment]
If you look at [the README](https://github.com/rmotr-group-projects/social-network-inheritance/blob/master/README.md) for this project it states that new Posts should have *no user associated with them* at first. Therefore they shouldn't automatically set a `self.first_name` and `self.last_name`
In fact Post objects shouldn't store any names, that information should be stored in the user that is eventually associated with the post via the `set_user` method. You can then access that information in your `__str__` methods via `self.user.first_name` and `self.user.last_name`

Hope that helps, if you need more clarification let me know.

**Comment by santiagobasulto** [comment]
@rlrogers can I close this one?

**Comment by rlrogers** [comment]
Yep! Thanks
