### ISSUE TITLE
HTTP practice, redirect requests

### ISSUE THREAD

**Issue by selmabensaid** [rmotr-curriculum/post-your-question-questions#131]
I get a key error when I run the test. Can you help me understand what's wrong with my code?

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
def perform_redirect_request():
    """Perform a request to a redirect URL and return the Location header that come in the response"""
    # HINT: you should use the allow_redirects parameter while doing the request
    url = 'https://httpbin.org/redirect/1'
    response=requests.get('https://httpbin.org/redirect/1', allow_redirects=True)
    return (dict(response.headers))['Location']

```

**Comment by jsymons** [comment]
You need to set `allow_redirects=False` by setting it to `True` requests doesn't let you see the redirect header, it automatically handles the redirect on its own.
