### ISSUE TITLE
Why do i get the below error in the test, when i am outputting the correct number as palindromic

### ISSUE THREAD

**Issue by asurania** [rmotr-curriculum/post-your-question-questions#137]
tests.py:85: in test_is_palindromic
    assert is_palindromic(121) is True
E   assert 121 is True
E    +  where 121 = is_palindromic(121)

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
def is_palindromic(n):
    x = str(n)
    y = x[::-1]
    y= int(y)
    while n != y:
        n +=1
        x = str(n)
        y = x[::-1]
        y= int(y)
        n=int(n)
    print (n)
    return n
    
is_palindromic(112)
```

**Comment by santiagobasulto** [comment]
@asurania I think you're overcomplicating this problem. You have already reversed the string in `y`. It's  just as simple as:

```python
def is_palindromic(n):
    x = str(n)
    y = x[::-1]
    return x == y
```

**Important:** Try using better names for your variables. `x`, `y`, etc don't say much. Try to give them a name that reflects what they are or what they're storing. Example:

```python
def is_palindromic(n):
    string_number = str(n)
    reversed = string_number[::-1]
    return string_number == reversed
```
