### ISSUE TITLE
Not able to do any one of the assignments of Class1 and Class2

### ISSUE THREAD

**Issue by ramrajkonuganti** [rmotr-curriculum/post-your-question-questions#138]
I couldn't complete even 1 assignment of all the class1 and class 2 assignments by myself. Some of the questions were hard for me to understand and remaining logics were hard to understand. Is this normal ? or am I lacking at something ? Help me out! 

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by jsymons** [comment]
Discussed in mentor session.
