### ISSUE TITLE
String syntax for skipping to parts

### ISSUE THREAD

**Issue by MoodyG** [rmotr-curriculum/post-your-question-questions#139]
In the lesson example given related to string slices, with string being s = "ABCDEFG", the call of s[1:7:2] returns BDF.  The unclear part is the 7.  Does this mean that as the string is only a length of 7, the count returns back down the string to -2, or F and then stops?  Why wouldn't it be BDFF if that's the case?  When would someone use something like this? 

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by zonagilreath** [comment]
Here's where to read about slicing/indexing in the python docs:
https://docs.python.org/3.7/library/stdtypes.html#sequence-types-list-tuple-range
It doesn't mention strings specifically there, but it works the same.

**Comment by aalrehn** [comment]
Here is an explanation of slices in python and it discusses the issue you want to address

https://www.pythoncentral.io/cutting-and-slicing-strings-in-python/

**Comment by MoodyG** [comment]
got it, I think the issue was remembering that 7 in this case is not included, but the documentation helped me understand the concept of stride in this case.  Thanks.
