### ISSUE TITLE
For the Football Github assignment

### ISSUE THREAD

**Issue by branhoff** [rmotr-curriculum/post-your-question-questions#14]
I tried to work on this on Sunday but I couldn't figure out how to integrate my cloud 9 account to my github. Jason mentioned in class there was some kind of step-by-step document explaining how to set this up. Could someone direct me to that?

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python

```

**Comment by jsymons** [comment]
https://learn.rmotr.com/python/rmotrcom-group-projects-guide/introduction/cheat-sheet is the cheat sheet for the whole pulling from/pushing to github process.

**Comment by branhoff** [comment]
That is helpful. The problem we're having is that we can't create new cloud 9 accounts. I think it has to be done with AWS (I think) and the simple login step doesn't make sense for that.

**Comment by santiagobasulto** [comment]
@branhoff I'll resend the invite right away and see if you can create an account that way. You'll be in our team.
