### ISSUE TITLE
Passing 'JUO' test

### ISSUE THREAD

**Issue by swhalley9** [rmotr-curriculum/post-your-question-questions#140]
Hello! I am struggling with determining how to figure out how to pass the 'None' test at the bottom. I have attempted adding another if statement regarding the left and right values, an elif, changing the total to None, along with several other things, but nothing has panned out. 

Let me know your thoughts. I know a student passed the test at the end of the lesson and it was fairly simple. I more or less want to learn from my mistakes and move on. 

Thanks! 

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
def get_value(char):
    if char == 'I':
        return 1
    if char == 'V':
        return 5
    if char == 'X':
        return 10
    if char == 'L':
        return 50
    if char == 'C':
        return 100
    if char == 'D':
        return 500
    if char == 'M':
        return 1000

    #if there is no 'else' then it will automatically return None
    
def parse_roman(roman):
    total = 0
    # index = 0

    for index, letter in enumerate(roman):
        left_char = letter
        if index < len(roman) - 1:
            right_char = roman[index+1]
        else:
            right_char = 'I'

        left_value = get_value(left_char)
        right_value = get_value(right_char)
        #print('{} = {}, {} = {}'.format(left_char,left_value, right_char,right_value))
        if left_value < right_value:
            left_value *= -1
            
        total += left_value
    print(total)
    return total

assert type(parse_roman('I')) == int
assert parse_roman('V') == 5
assert parse_roman('XXIV') == 24
assert parse_roman('I') == 1
assert parse_roman('JUO') == None
print('Happy little test passing statement here')
```

**Comment by jsymons** [comment]
In your `parse_roman` function you should have an if statement to check if you get `None` back from `get_value` (meaning that the char wasn't a valid roman numeral), if you do get a `None` back then you in turn `return None`. So basically if `left_value` or `right_value` is `None` you should `return None`.

**Comment by swhalley9** [comment]
Right. I was banging my head against this and then got to the section about 'break.' I fixed it by simply adding this prior to the last if statement: 

if left_value is None:
            total = None
            break

Break is what I was missing. Thanks!
