### ISSUE TITLE
Stuck on assignment_2 on the first projects

### ISSUE THREAD

**Issue by IsaiahDB** [rmotr-curriculum/post-your-question-questions#143]
I have tried several ways that returned values but I was able to return keys and value. I also do not see how I can make the function return a dictionary while at the same time group the similar values.  

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by jsymons** [comment]
Sorry for the delay in catching this, if you are still having issues with this problem please re-open and supply an example of your code.
