### ISSUE TITLE
Uploading to GitHub from terminal

### ISSUE THREAD

**Issue by swhalley9** [rmotr-curriculum/post-your-question-questions#144]
Each time I try to upload a changed file to GitHub from notebooks.ai through the terminal, I get an error when I write a description for each word that I type. I know how to manually upload it by just editing the forked file and writing the description within the website, but I want to get this down so I can be more efficient. Do I have the push the file after the description is finished too? Do I need to put the description in quotes? Just trying to remember what we went through in class. 

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
git add 'file_name'

git commit -m 'description'


```

**Comment by jsymons** [comment]
First you `add`, then you `commit`, then you `push`. Example:
```shell
git add changed_file.py
git commit -m "My fancy commit message"
git push
```
