### ISSUE TITLE
Returns in Python functions

### ISSUE THREAD

**Issue by topher-allen** [rmotr-curriculum/post-your-question-questions#146]
Hi quick question about functions in general: I've had some practice with other languages (Java, C++) and void functions are obviously pretty common. I just finished the 'return vs print' lesson. So the concept of a void function doesn't exist in Python? AKA I need to format all of my functions to ultimately return something? 

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by jsymons** [comment]
If you don't explicitly return something your function will default to returning `None`, so you are not required to provide a return value and you won't always want one.

**Comment by topher-allen** [comment]
It seemed like the lecture suggested we should always return a value in our functions? But we never want to put a print statement in any function either way, correct?

**Comment by jsymons** [comment]
You only need to return if you want to get something out of it. I like to stay away from saying 'never' you usually don't want a print statement in a function though it can be helpful for quick debugging.
