### ISSUE TITLE
Spaghetti code vs proper code 

### ISSUE THREAD

**Issue by nessadc** [rmotr-curriculum/post-your-question-questions#147]
I feel like I am not writing the most concise code. My solution for  'animal multi search' exercise is horrendous compared to the posted solution. I seem to have this issue when accessing nested collections, I feel as if I'm "bruteforcing" my code to work and I know this is not proper Python mindset. There's a lot of repetition for example. A lot of these more advanced nested collections, I want to write smaller 'helper' functions, is this a good habit to develop or should I try to limit how many functions I should use? I cannot tell how 'simple' or 'complicated' each of these exercises are supposed to be. They seem simple on the surface but when actually coding, I feel like I'm rambling on. 

 Is this something that's just going to get better at practice? Should I just keep practicing similar problems like the 'animal multi-search', 'eldest customer per state', and 'add book to purchase'? 

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# Write your function here!
def search_animals(list_of_animals, given_name=None, animal_type=None):
    found_animals = []
    if animal_type and given_name: # search both things
        for animal in list_of_animals:
            if animal_type in animal['animal_type'] and given_name in animal['given_name']:
                found_animals.append(animal)
    elif given_name:
        for animal in list_of_animals:
            if given_name in animal['given_name']:
                found_animals.append(animal)
    elif animal_type:
        for animal in list_of_animals:
            if animal_type in animal['animal_type'] or animal_type in animal['street_name']:
                found_animals.append(animal)
    else:
        return list_of_animals
    
    return found_animalsre (if any)
```

**Comment by jsymons** [comment]
So here's the thing, nobody writes perfect code the first time. What you want to do is to write something that works. Once you have something that works and passes tests you can then refactor it into a better solution secure that if you *do* break something you have the tests there to back you up and let you know.

So what you have here is a good first pass, but once you've got this running to this point you can probably see there's a lot of similarity between the branches of your if. You could probably refactor it into a single loop and then put your conditions inside.

There is nothing wrong with using helper functions, in fact I'd rather see ten 10-line helper functions than like a 100+ line single function.
