### ISSUE TITLE
Completed exercises not saved

### ISSUE THREAD

**Issue by chinnappa-raju** [rmotr-curriculum/post-your-question-questions#149]
I want to see my completed exercises. They are not being saved though the results are being recorded. How can i retrieve them?

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by santiagobasulto** [comment]
I just checked this @chinnappa-raju. Which ones are you having issues with? I see several exercises completed under your account. Which ones are failing?
