### ISSUE TITLE
OOP-Hangman Project

### ISSUE THREAD

**Issue by AndyDeNike** [rmotr-curriculum/post-your-question-questions#16]
Explanation is in code

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)#I am stuck on a section of OOP project Hangman.  The instructions explain that HangmanGame class has one classmethod select_random_word that receives a list of words and selects one randomly.

#I do not understand how to implement this classmethod properly and am unsure how to properly pass this test:  

def test_start_new_game_initial_state_with_number_of_guesses():
    game = HangmanGame(['Python'], number_of_guesses=3)

    assert game.remaining_misses == 3
    assert isinstance(game.word, GuessWord)
    assert game.previous_guesses == []
    
#this is my current code for the class:

class HangmanGame(object):
    
    def __init__(self, word_list, number_of_guesses=5):
        
        self.word_list = word_list 
        self.remaining_misses = number_of_guesses
        self.previous_guesses = []
        
    def select_random_word(self):
            if self != []:
                return random.choice(self)
            raise InvalidListOfWordsException()
        
    def word(self):
        pass

# dont know if you can access it from this link but i posted it in case: 
# https://ide.c9.io/denikeandrew/oop-hangman-game
```

**Comment by santiagobasulto** [comment]
Hey Andrew! You're almost there. The `select_random_word` method should be a class method, so it doesn't accept `self` and it should have the decorator `@classmethod`. Something like:

```python
    @classmethod
    def select_random_word(cls, word_list):
        if not word_list:
            raise InvalidListOfWordsException()
        return random.choice(word_list)
```
With that method in place, you should select 1 random word from the `word_list` that you received, in your __init__ method.

**IMPORTANT:** Watch out for your indentation. I see different indentation levels in your pasted code, make sure you're not mixing tabs and spaces:

![image](https://user-images.githubusercontent.com/872296/39663171-accff1fe-5044-11e8-958f-9b673eeba2d5.png)

**Comment by AndyDeNike** [comment]
Thank you for guidance on class variables but how would I implement the '**word**' method to properly evaluate **assert isinstance(game.word, GuessWord)**?  

My current code: 
```
class HangmanGame(object):
    WORD_LIST = ['rmotr', 'python', 'awesome']
    
    def __init__(self, word_list=WORD_LIST, number_of_guesses=5):
        self.remaining_misses = number_of_guesses
        self.previous_guesses = []
        self.word_list = word_list
        
    @classmethod 
    def select_random_word(cls, word_list):
        if not word_list:
            raise InvalidListOfWordsException()
        return random.choice(word_list)
        
        
    def word(self):
        the_word = GuessWord(self_random_word(self.word_list))
        return the_word
```

It appears the test would have me create a **GuessWord** object through the **word** method?  Not sure how to properly integrate the 'self_random_word' as I keep getting the warning 'Undefined variable '**self_random_word**'?  Thanks for your time!

**Comment by santiagobasulto** [comment]
`word` shouldn't be a method, it's an attribute of `HangmanGame`. Your word method looks good, but again, it should be an attribute. So I'd just combine it in the `__init__` method like:

```python
  def __init__(self, word_list=WORD_LIST, number_of_guesses=5):
        self.remaining_misses = number_of_guesses
        self.previous_guesses = []
        self.word_list = word_list
        self.word = GuessWord(self.select_random_word(word_list))
```

Btw, for this project I think it's best to start with `test_guess_attempt.py` and `test_guess_word.py` (in that order) before `test_hangman_game.py`.

**Comment by AndyDeNike** [comment]
awesome, thinking this will be the last question for this thread but, within my current code, https://ide.c9.io/denikeandrew/oop-hangman-game

 I am wondering how I can check to see the conditions for GameWonException have been met without returning the code and exiting the Guess method; to put it antoher way, how can I have the test requirement of returning 'True' for is_hit() be met and still raise the GameWonException?:

```
def guess(self, letter_guess):
        self.previous_guesses.append(letter_guess.lower())
        
    
        if self.word.perform_attempt(letter_guess).is_hit():
            return self.word.perform_attempt(letter_guess)
            
            #if ("*" not in self.word.masked):
                #raise GameWonException()
        else: 
            self.remaining_misses -= 1
            return self.word.perform_attempt(letter_guess)
```
 
The section of test I am refering to is: 

```
def test_game_wins_first_try():
    game = HangmanGame(['aaa'])

    with pytest.raises(GameWonException):
        game.guess('a')

    assert game.is_finished() is True
    assert game.is_won() is True
    assert game.is_lost() is False

    assert game.remaining_misses == 5
    assert game.previous_guesses == ['a']
    assert game.word.masked == 'aaa'
```

**Comment by AndyDeNike** [comment]
awesome, thinking this will be the last question for this thread but, within my current code, https://ide.c9.io/denikeandrew/oop-hangman-game

I am wondering how I can check to see the conditions for GameWonException have been met without returning the code and exiting the Guess method; to put it another way, how can I have the test requirement of returning '**True**' for **is_hit()** be met and still raise the **GameWonException**?:

def guess(self, letter_guess):
        self.previous_guesses.append(letter_guess.lower())
        
    
        if self.word.perform_attempt(letter_guess).is_hit():
            return self.word.perform_attempt(letter_guess)
            
            #if ("*" not in self.word.masked):
                #raise GameWonException()
        else: 
            self.remaining_misses -= 1
            return self.word.perform_attempt(letter_guess)

The section of test I am refering to is:

def test_game_wins_first_try():
    game = HangmanGame(['aaa'])

    with pytest.raises(GameWonException):
        game.guess('a')

    assert game.is_finished() is True
    assert game.is_won() is True
    assert game.is_lost() is False

    assert game.remaining_misses == 5
    assert game.previous_guesses == ['a']
    assert game.word.masked == 'aaa'
