### ISSUE TITLE
replit link 1 class

### ISSUE THREAD

**Issue by deboragaleano** [rmotr-curriculum/post-your-question-questions#17]
I was looking for the replit link of the game (1st class), I found one in the word doc "student resources" but it's not the same one that was done in class. Thank you!

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by santiagobasulto** [comment]
Hey Deby! Was it one that Jason used or from our videos?

**Comment by deboragaleano** [comment]
Hi Santiago! It's the one Jason has used for the fun guessing game! I'm still struggling to finish the while loops exercises and wanted to check the code for this. Thank you!

**Comment by santiagobasulto** [comment]
Oh, yes, definitively. This one, right?  https://repl.it/@santiagobasulto/HummingBleakZebraswallowtailbutterfly

**Comment by deboragaleano** [comment]
I think this is the one posted under the video recording but in the actual video during class, the replit was more elaborate. 

It would be great to have the link of every replit under the youtube video maybe or on the class "card". I don't have the same time zone so I always review it after class and if I'm not online or on the chat, I don't get the information. 

Thank you!
