### ISSUE TITLE
Unit one not showing completed

### ISSUE THREAD

**Issue by swb304** [rmotr-curriculum/post-your-question-questions#19]
My dashboard is not showing unit 1 completed; however, I completed all of the assignments. It's showing 14/16 completion.

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by santiagobasulto** [comment]
Checking!

**Comment by swb304** [comment]
Still showing not completed (14/16)
![image](https://user-images.githubusercontent.com/38900127/40005846-96df5576-575e-11e8-841a-90a4f935bcd1.png)

**Comment by santiagobasulto** [comment]
Hello @swb304! We are still investigating the issue, might be an issue. Can you please email me the account you used to create your account santiago@rmotr.com. We'll figure it out soon 😁 .

**Comment by santiagobasulto** [comment]
Hey @swb304! Just checked your cards for the first unit and I still see 2 that are not completed yet:

![image](https://user-images.githubusercontent.com/872296/40070704-dbea63f2-583c-11e8-873e-48e39cfbfaa8.png)

I'ts under Class 2, scroll all the way to the right.

**Comment by swb304** [comment]
I see now, I thought that part was under Unit 2, but I was confused, sorry.. Thanks!

**Comment by santiagobasulto** [comment]
No problem!
