### ISSUE TITLE
Are there videos with all of the topics for the Python overview?

### ISSUE THREAD

**Issue by useraddmario** [rmotr-curriculum/post-your-question-questions#2]
As I went through the last part of the Python Overview(I think) and the String Concatenation sections I was only presented with the programming interface sandboxes no videos.  Is that correct or was I missing something?  Before that it seemed like a video per "programming sandbox.  It seemed like there were "questions" for the various subjects, but little to no explanation.  Hopefully I am explaining this correctly.

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by santiagobasulto** [comment]
Hello @useraddmario! Thanks for reporting this, we've already fixed it.
