### ISSUE TITLE
whats wrong with my code

### ISSUE THREAD

**Issue by mohabouh** [rmotr-curriculum/post-your-question-questions#20]
it returns the right outcome

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your def common_values(tup1,tup2):
    Union = tup1 | tup2
    print(Union)

common_values({1,5,7,1,24},{1,2,3,4})code here (if any)
```

**Comment by santiagobasulto** [comment]
@mohabouh you're printing the value, not returning it! There's a "return vs print" video 😁
