### ISSUE TITLE
Unable to complete "Submit Solution"

### ISSUE THREAD

**Issue by swb304** [rmotr-curriculum/post-your-question-questions#21]
The submit solution seems to be not working.  I submitted the following code, and the submit solution keeps running non-stop.  I used PythonTutor.com to verify my code works.

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
def insert_dashes(a_string):
    count = 1
    dash_string = ''
    while count <= len(a_string):
        char = a_string[count - 1]
        dash_string += char
        if count % 3 == 0:
            dash_string += '-'
        count += 1
    return dash_string
        
print(insert_dashes('blueman'))
```

**Comment by santiagobasulto** [comment]
Both seem to be working fine. Yours too:

![image](https://user-images.githubusercontent.com/872296/40085634-2b78ac0e-5869-11e8-901c-44f366b44907.png)

What do you see? Any errors?

**Comment by swb304** [comment]
It just continues to spin and never completes. Same thing when I hit "Run Code".
![image](https://user-images.githubusercontent.com/38900127/40086360-b3684c38-5863-11e8-95b9-dbf008351a17.png)

**Comment by santiagobasulto** [comment]
Thanks @swb304. I'll investigate. It's odd. Do you know if it happens on any other assignment?
