### ISSUE TITLE
How to "inpsect the headers that came with the response" ? 

### ISSUE THREAD

**Issue by AndyDeNike** [rmotr-curriculum/post-your-question-questions#26]
In the final test of the 'http-practice' project, I am unclear on how we are supposed to inspect the headers or where the response is viewed.  

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
'''
7. Inspect headers during a redirect request

$ py.test tests.py -k test_7

In this case you'll have to perform a GET request to the given URL (which already handles the redirect). The status code that you'll get is going to be inside the 3XX group which means 'Redirection'.

Inspect the headers that came in the response and return the "Location" one. Make sure to use the allow_redirects parameter while performing the request, to work with the response that comes before the redirect is done.
'''

def perform_redirect_request():
    """Perform a request to a redirect URL and return the Location header that come in the response"""
    # HINT: you should use the allow_redirects parameter while doing the request
    url = 'https://httpbin.org/redirect/1'
    response = requests.get(url, allow_redirects=False)
    return response
    
# TEST 

def test_7_perform_redirect_request():
    location_header = perform_redirect_request()

    assert location_header == '/get'
```

**Comment by jsymons** [comment]
From the requests library documentation: http://docs.python-requests.org/en/master/user/quickstart/#response-headers

You can view the response content via the various attributes of the object returned by the `get`, so `response` in the context of your code.

**Comment by AndyDeNike** [comment]
how would i go about viewing it?  

my current code: 

```
def perform_redirect_request():
    """Perform a request to a redirect URL and return the Location header that come in the response"""
    # HINT: you should use the allow_redirects parameter while doing the request
    url = 'https://httpbin.org/redirect/1'
    response = requests.get(url, allow_redirects=True)
    return response.headers

# TEST 

def test_7_perform_redirect_request():
    location_header = perform_redirect_request()
    
    from pprint import pprint 
    pprint(location_header)

    assert location_header == '/get'

```

the pprint returns:  

`tests.py {'Access-Control-Allow-Origin': '*', 'Connection': 'keep-alive', 'Date': 'Wed, 23 May 2018 02:52:37 GMT', 'Server': 'gunicorn/19.8.1', 'Via': '1.1 vegur', 'Content-Length': '212', 'Content-Type': 'application/json', 'Access-Control-Allow-Credentials': 'true'}`

which doesnt seem to contain a 'Location' key as given in the github RMOTR solution (though I may be looking in the wrong place).

**Comment by jsymons** [comment]
You've got `allow_redirects` set to `True` which means you're ultimately getting the page **after** the redirect, you need to set it to `False` instead.

**Comment by AndyDeNike** [comment]
@jsymons so, we have the _url = 'https://httpbin.org/redirect/1'_ and in the next line, 
_response = requests.get(url, allow_redirects=False)_
what exactly is going on in that line in relation to that first line?

**Comment by jsymons** [comment]
`url` is the url that the `requests.get` is going to retrieve.
You could also write it as
```python
response = requests.get('https://httpbin.org/redirect/1', allow_redirects=False)
```
