### ISSUE TITLE
need help with assignment 3 of the project

### ISSUE THREAD

**Issue by mohabouh** [rmotr-curriculum/post-your-question-questions#29]
I did assignment 1 and 2 but need help with assignment 3 of the project

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by jsymons** [comment]
Going to need a little more detail than that to be able to help.

**Comment by mohabouh** [comment]
can we do zoom session ?

**Comment by mohabouh** [comment]
need to create a function which will return the players grouped by country, and per each country, grouped by position.

**Comment by jsymons** [comment]
This is *very* similar to assignment 2.
In assignment 2 you were essentially doing (Note: this is just psuedo code):
```
for player in players:
    if position not in dictionary:
        create position key in dictionary
    insert player at position
```
For assignment 3 you just need to add an extra step:
```
for player in players:
    if country not in dictionary:
        create country key in dictionary
    if position not in country:
        create position key in country
    insert player at position in country
```

If you still need help with this you can catch me during mentor hours tomorrow night (8pm-11pm Eastern) for a zoom session.
