### ISSUE TITLE
Dashboard interface issues

### ISSUE THREAD

**Issue by databaseadmins** [rmotr-curriculum/post-your-question-questions#3]
My dashboard continues to not show progress - I don't want to keep posting "It doesn't work" statements -- can you just tell me when it's resolved so I can confirm?

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by martinzugnoni** [comment]
Hi Burt. We've just pushed some fixes to production that should finally resolve this issue. Can you please double check your dashboard shows all progress, and also the progress is updated when you finish a lesson in Learn? Thank you very much for you time! 👏

**Comment by databaseadmins** [comment]
The interface is broken now.; I can't see my lessons -- sorry for the bad news.

**Comment by databaseadmins** [comment]
![image](https://user-images.githubusercontent.com/19609022/35823906-147c62bc-0a7f-11e8-879b-adb377e0bb8e.png)

**Comment by santiagobasulto** [comment]
@databaseadmins I think it's fixed now, can you check?
