### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by aderawill** [rmotr-curriculum/post-your-question-questions#34]
Cannot figure why this is not splitting

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
emails_string = """
 Jon Snow <jon@starks.com>,
 arya@starks.com   ,
 Eddard "Ned" Stark <ned@starks.com>,
 sansa@starks.com,
 jon@starks.com,
    Arya No Face <arya@starks.com>
 """
#print(emails_string)
       

def parse_emails(emails_string):

    email_split = emails_string.split(" , ")
    print(email_split)   
```

**Comment by santiagobasulto** [comment]
Hey @aderawill ! Python is REALLY sensitive to the strings you pass. In this case, your split command has the parameter `" , "`, with two whitespaces at the beginning and end. Try removing those spaces and it should work `emails_string.split(",")`.

**Comment by jsymons** [comment]
@santiagobasulto Sorry, should have gotten this closed, already covered this with him in a mentor session

**Comment by santiagobasulto** [comment]
👍
