### ISSUE TITLE
Pytest or virtualenv problems

### ISSUE THREAD

**Issue by BJohnAmbrose** [rmotr-curriculum/post-your-question-questions#35]
brianjbeegan:~/workspace (master) $ pip install pytest
Downloading/unpacking pytest
  Downloading pytest-3.6.2-py2.py3-none-any.whl (195kB): 195kB downloaded
Downloading/unpacking pluggy>=0.5,<0.7 (from pytest)
  Downloading pluggy-0.6.0-py2-none-any.whl
Downloading/unpacking atomicwrites>=1.0 (from pytest)
  Downloading atomicwrites-1.1.5-py2.py3-none-any.whl
Downloading/unpacking funcsigs (from pytest)
  Downloading funcsigs-1.0.2-py2.py3-none-any.whl
Downloading/unpacking py>=1.5.0 (from pytest)
  Downloading py-1.5.4-py2.py3-none-any.whl (83kB): 83kB downloaded
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/dist-packages (from pytest)
Downloading/unpacking more-itertools>=4.0.0 (from pytest)
  Downloading more_itertools-4.2.0-py2-none-any.whl (45kB): 45kB downloaded
Downloading/unpacking six>=1.10.0 (from pytest)
  Downloading six-1.11.0-py2.py3-none-any.whl
Downloading/unpacking attrs>=17.4.0 (from pytest)
  Downloading attrs-18.1.0-py2.py3-none-any.whl
Installing collected packages: pytest, pluggy, atomicwrites, funcsigs, py, more-itertools, six, attrs
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 206, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 193, in clobber
    os.makedirs(destsubdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/_pytest'

Storing debug log for failure in /home/ubuntu/.pip/pip.log
brianjbeegan:~/workspace (master) $ 

dont know what the issue is. I feel like I have about zero understanding of how things work in the virtualenv.

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by jsymons** [comment]
It looks like you didn't setup your virtual environment before trying to do your `pip install`

You need to do `mkvirtualenv <environment name>` **before** you run pip
