### ISSUE TITLE
Problem solving this flask question using request......

### ISSUE THREAD

**Issue by kufopi** [rmotr-curriculum/post-your-question-questions#36]
I'm at a loss on how to start

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)@app.route('/user')
def search_user():
    """
        Implement a view that receives a '?search=' query parameter in the URL,
        and returns the amount of users in the given users_list that contains
        that search string in their names.
        i.e: /user?search=mo will return 'Found 2 users that match with search "mo"'
    """
    # HINT: to access the query params you'll need to use request.args.get()
    # function imported from flask
    users = ['Jack', 'Morgan', 'Moe', 'Steve']
    pass
```

**Comment by ivanzugnoni** [comment]
FIrst step is to take the given `search` pattern that is sent to you as a HTTP GET parameter. You can do it like this:

```python
search = request.args.get('search')
```

Once you have the search string, you have to loop through the given `users` list (either with a for loop or a list comprehension) and count how many of the string names inside the list contain the `search` pattern.

i.e: If given `search` is `Mo`, the names inside `users` list that contain that search are "Morgan" and "Moe", so you have to return the string: `'Found 2 users that match with search: "Mo"'`
