### ISSUE TITLE
pytest virtenv

### ISSUE THREAD

**Issue by BJohnAmbrose** [rmotr-curriculum/post-your-question-questions#37]
Im still getting an error stating that there is no module pytest

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by jsymons** [comment]
First setup your environment:
```
mkvirtualenv my_environment_name
pip install -r requirements.txt
```
You can then run tests:
```
py.test tests.py
```
