### ISSUE TITLE
pytest virtenv

### ISSUE THREAD

**Issue by BJohnAmbrose** [rmotr-curriculum/post-your-question-questions#38]
(hangman)brianjbeegan:~/workspace (master) $ pip install -r dev-requirements.txt
Requirement already satisfied (use --upgrade to upgrade): pytest==3.4.1 in /home/ubuntu/.virtualenvs/hangman/lib/python2.7/site-packages (from -r dev-requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): tox==2.7.0 in /home/ubuntu/.virtualenvs/hangman/lib/python2.7/site-packages (from -r dev-requirements.txt (line 2))

still get the no module error when i run

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by jsymons** [comment]
First off, instead of creating new issues please just add a new comment to the existing thread.

Secondly please give a link to your c9

**Comment by BJohnAmbrose** [comment]
sorry i was posting via rmotr. 
https://ide.c9.io/brianjbeegan/hangman

**Comment by jsymons** [comment]
I need you to approve my access request, should be under the collaborate section on the top rlght of your c9 window

**Comment by BJohnAmbrose** [comment]
i see your message but i dont see a request or how to approve it in the collaborate tab
