### ISSUE TITLE
py.test: command not found

### ISSUE THREAD

**Issue by zonagilreath** [rmotr-curriculum/post-your-question-questions#39]
Hi, whenever I try to run `py.test test_guess_attempt.py` on the c9 bash terminal I get the above error It worked for me previously and I don't know ow I would have changed my virtualenv or anything. 

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python

```

**Comment by jsymons** [comment]
Since you said in slack that this is resolved can you please go ahead and close this?

**Comment by zonagilreath** [comment]
Yup, sorry, wasn't sure where this question even posted.

**Comment by santiagobasulto** [comment]
I **just** got the email. Maybe Github was a little bit overloaded?
