### ISSUE TITLE
Access?

### ISSUE THREAD

**Issue by itoffensedefense** [rmotr-curriculum/post-your-question-questions#4]
I've lost all access to the content and work leading up to today.  I managed to watch a few of the videos and knock out the "Hello " + "world" task, but now I can't see any of the content.  Only that there is a class starting at 9pm this evening.

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by santiagobasulto** [comment]
Should be fixed!
