### ISSUE TITLE
Immutable string

### ISSUE THREAD

**Issue by cpjain2007** [rmotr-curriculum/post-your-question-questions#40]
Strings are immutable in python but it looks like string variable can be pointed to another string, shown in below example.
Why do we call it immutable as its value can be changed? or immutable means that object in memory can't be changed if it was initially saved as a string 

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
'''
Strings are immutable in python but it looks like string variable can be pointed to another string, shown in below example.
Why do we call it immutable as its value can be changed? or immutable means that object in mmeory cann't be changed if it was initially saved as a string 
'''

string_a = 'aaaa'
string_b = 'bbbb'

string_a = string_b
print(string_a)


```

**Comment by santiagobasulto** [comment]
Hello @cpjain2007! You're exactly right when you say:

> or immutable means that object in memory can't be changed if it was initially saved as a string

The real, underlying value of a variable can't be changed. You can point it to other variables, but the value can't be changed. This is useful for example if you're passing a value to a function:

```python
my_string = "hello world"

shady_function(my_string)
```

You rest assured that NOBODY will be able to modify what you have in `my_string`.

**Comment by cpjain2007** [comment]
Thank you. So it looks like if it is immutable this will be always passed by value in the function otherwise it will by reference.

**Comment by santiagobasulto** [comment]
Good point! Actually Python isn't "pass by value" or "pass by reference" (as most traditional languages): it's usually said "pass by object", which is like "passing the reference to the object". The mutable / immutable effect is just due to the nature of the object. If an object is immutable, it won't be changed, regardless of the way it's passed.

**Comment by cpjain2007** [comment]
Got it. thank you
