### ISSUE TITLE
project #1

### ISSUE THREAD

**Issue by mattmm41286** [rmotr-curriculum/post-your-question-questions#44]
The CSV for project one with the list of players has over 8000.  How many are we supposed to do the assignment for?  I am watching Santiago walk through, and it looks like his only had 14?  

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python

```

**Comment by jsymons** [comment]
Your code should be designed such that the number doesn't matter, it just iterates over it all.

**Comment by mattmm41286** [comment]
Okay thanks
