### ISSUE TITLE
More exercises?

### ISSUE THREAD

**Issue by mrbaker1917** [rmotr-curriculum/post-your-question-questions#49]
I am done the prep work. Are there other lessons I can do before classes start on 6 August 2018?

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by santiagobasulto** [comment]
Awesome Mark! Congratulations. You can start with all the lessons on Unit 1 before the first class. Starting with Valid Passwords.

**Comment by mrbaker1917** [comment]
Thanks, Santiago. I did the valid passwords lesson. Moving on....
