### ISSUE TITLE
There were supposed to be extra lessons posted per the meeting last night.

### ISSUE THREAD

**Issue by databaseadmins** [rmotr-curriculum/post-your-question-questions#5]
I don't see them.  Did they get posted?

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by martinzugnoni** [comment]
We received the question, Burt. Is there any issue?

**Comment by databaseadmins** [comment]
Yes there is an issue.  Last night in class they mentioned that there were going to be some new lessons added but I don't see anything new.  I'm wondering if I misunderstood or if they never got added.
