### ISSUE TITLE
rmotrgram project question

### ISSUE THREAD

**Issue by vckelly** [rmotr-curriculum/post-your-question-questions#50]
Hi, 

I am having a problem running the tests for the rmotorgram project. It looks like the factories.py file is importing class named factory in line 1. From what I can tell, there is no file / directory referenced in the import statement, and my c9 environment is complaining about 'no module named factory' (ImportError). 

Do you know what might be the issue?

Thanks, 

Connor

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
import factory
from datetime import datetime

from social_network import accounts, posts


class UserFactory(factory.Factory):
    class Meta:
        model = accounts.User

    first_name = factory.Iterator(['Kevin', 'Joe', 'Ervin', 'Daniel'])
    last_name = factory.Iterator(['Watson', 'Fowler', 'Roberts', 'Wiley'])
    email = factory.LazyAttribute(lambda u: '{}.{}@fake-domain.com'.format(
        u.first_name, u.last_name))


class PostFactory(factory.Factory):
    class Meta:
        model = posts.Post

    text = 'Sample post text'
    timestamp = datetime(2017, 1, 10)


class TextPostFactory(PostFactory):
    class Meta:
        model = posts.TextPost


class PicturePostFactory(PostFactory):
    class Meta:
        model = posts.PicturePost

    image_url = 'http://fake-domain.com/images/sample.jpg'


class CheckInPostFactory(PostFactory):
    class Meta:
        model = posts.CheckInPost

    latitude = -34.603722
    longitude = -58.381592

```

**Comment by santiagobasulto** [comment]
We're using a new library to create those factories, it's called `factory-boy` and is under [requirements.txt](https://github.com/rmotr-group-projects/social-network-inheritance/blob/master/requirements.txt#L1). Can you try doing `pip install factory-boy` to see if it fixes it?

**Comment by vckelly** [comment]
Santiago,

My fault for not reading the requirements, I saw that earlier today and just got done with my code. Thanks!

**Comment by santiagobasulto** [comment]
Amazing, congrats then! 😁
