### ISSUE TITLE
feedback more so than a question

### ISSUE THREAD

**Issue by jjk235** [rmotr-curriculum/post-your-question-questions#51]
This is more of a feedback than a question. I'm doing my first trial week of your ML program and love it so far and plan to sign up for the four months. Your instructions are very clear with great visual aid; however, sometimes I find that I'm itching for some actual jargon usage. It's good to have visual aid where you're pointing at two different boxes representing parameters and saying 'this binds to this' but even something as simple as distinguishing by jargons (e.g. formal vs actual parameters) would allow us to have more intelligent conversations about coding in the future, I think. I'm starting to find that while I'm able to code for basic tasks as listed in your assignments, I'm not very good at explaining the structure of the code (e.g. point of execution, point of invocation) even though I know it'll work & do the things I want it to do. I find myself keep referring to a different textbooks to supplement my knowledge (as anyone really should, I suppose!). Even just throwing a couple of jargons around and saying, 'hey, if you wanna read up further on this stuff, here's a couple of keywords you could look into' that'd be incredibly helpful. Thank you so much!

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by santiagobasulto** [comment]
Hello @jjk235! Wow, thanks very much :) This is really useful. When you mention jargon, were you thinking about a glossary of terms, for example?

I've written down the idea of extra readings, we have a few, so I'll start adding them!

I'll leave this issue open so we can keep the discussion open. Thanks again!
