### ISSUE TITLE
Gists DB Project

### ISSUE THREAD

**Issue by vckelly** [rmotr-curriculum/post-your-question-questions#52]
Hi, 

I am having issues completing the search function for the Gists project. I am not sure how to properly get my parameters into the .exectute function being called on my DB object. I am getting these errors:

assert gist.github_id == '4232a4cdad00bd92a7a64cf3e2795820'
E       AttributeError: 'tuple' object has no attribute 'github_id'

cursor = db_connection.execute(SQL_QUERY, params)
E           sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 0, and there are 1 supplied.

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
from .models import Gist


def search_gists(db_connection, **kwargs):
    SQL_QUERY = 'SELECT * from gists'
    git_id = False

    if 'errormessage' in kwargs:
        pass
    
    if 'github_id' in kwargs:
        SQL_QUERY += ' WHERE github_id = ?'
        git_id = True   
    
    if 'created_at' in kwargs:
        if git_id:
            SQL_QUERY += ' AND WHERE created_at = ?'
        else:
            ' WHERE created_at = ?' 
    
        
    params = [vals for vals in kwargs.values()]
    
    if len(params) < 1:
        cursor = db_connection.execute(SQL_QUERY)

    else:
        cursor = db_connection.execute(SQL_QUERY, params)
        
    return cursor.fetchall()
```

**Comment by santiagobasulto** [comment]
Hey @vckelly ! From what I see you're missing the `SQL_QUERY +=` under the `if 'created_at' in kwargs`:

```python
 
    if 'created_at' in kwargs:
        if git_id:
            SQL_QUERY += ' AND WHERE created_at = ?'
        else:
            ' WHERE created_at = ?'   <<< MISSING SQL_QUERY +=
    
```

Can you try that way?
