### ISSUE TITLE
Need the result to be a dictionary with nested dictionaries

### ISSUE THREAD

**Issue by dackota** [rmotr-curriculum/post-your-question-questions#53]
Currently this is creating dictionaries by zipping squads_list with list1 but the end result is still a list with nested dictionaries. 

I know its because results starts out as a list but if I change it to a dict and change line 8 to results.update then the dictionaries just overwrite themselves instead of creating several dictionaries nested in the dictionary.

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python

def players_as_dictionaries(squads_list):
    list1 = ('number', 'position', 'name', 'date_of_birth', 'caps', 'club', 'country',
         'club_country', 'year')
    results = []
    
    for lists in squads_list:
        results.append(dict(zip(list1, lists)))
    
    
    return(results)


```

**Comment by santiagobasulto** [comment]
Hello @dackota! The solution is much simpler I think. You can "explicitly" pick each attribute from the player to create the dict inside your for loop. You'll end up with a much more readable solution. Example:

```python
def players_as_dictionaries(squads_list):
    results = []
    for player in squads_list:
        player_as_dict = {
            'number': player[0],
            'position': player[1],
            'name': player[2],
            ... etc ... 
        }
        results.append(player_as_dict)
    
    return results  # no need for parentheses here
```
