### ISSUE TITLE
Football Dictionaries - Test Failing

### ISSUE THREAD

**Issue by Jappandy** [rmotr-curriculum/post-your-question-questions#54]
Not sure why my code is failing. When I re-create the tests (asserts) right after the function it seems to do what the tests are asking; however, when I use the py. test tests. py -k assignment_1, for example, I get the following error:

AssertionError: assert {'caps': '', ...gentina', ...} == {'caps': '', '...gentina', ...}
E         Omitting 8 identical items, use -vv to show
E         Left contains more items:
E         {'dob': '(1908-10-23)23 October 1908 (aged 21)'}
E         Right contains more items:
E         {'date_of_birth': '(1908-10-23)23 October 1908 (aged 21)'}
E         Use -v to get the full diff

This is similar for all tests that are failing. I pushed the assignment to see if the error was just on my end, but Trevor didn't like me either :(

https://github.com/Jappandy/itp-u3-c2-football-dictionaries

Thank you for your help!

-Andrew

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by santiagobasulto** [comment]
Hey Andrew! Seems like you're not respecting the names expected by the tests. For example, tests are expecting `date_of_birth`, as you can see here: https://github.com/Jappandy/itp-u3-c2-football-dictionaries/blob/master/tests.py#L22

But you're setting `dob`: https://github.com/Jappandy/itp-u3-c2-football-dictionaries/blob/master/football_dictionaries/assignment_1.py#L28

**Comment by Jappandy** [comment]
Thank you so much!
