### ISSUE TITLE
Football Dict Project 

### ISSUE THREAD

**Issue by Jappandy** [rmotr-curriculum/post-your-question-questions#55]
Still waiting on "Test Passing" to get marked off. Everything was passed by Trevor. Not sure if this is checked manually, as I finished last night. Here is the URL : https://github.com/Jappandy/itp-u3-c2-football-dictionaries

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by santiagobasulto** [comment]
Hey @Jappandy! Have you folks submitted the PR? I can't see the ones created.

**Comment by Jappandy** [comment]
You don't see them? I'll try it again, but it trevor shows no errors. I did push the first time with an error, but after fixing it I see no error. Do I need to push again?

**Comment by Jappandy** [comment]
I see the pull requests here and looks good to go. https://github.com/rmotr-group-projects/itp-u3-c2-football-dictionaries/pulls

Or, am I to push to my own account, which doesn't seem right...

**Comment by santiagobasulto** [comment]
I'm investigating an issue on our side. Yours looks good, I'll let you know!
