### ISSUE TITLE
Trouble Accessing Classes / Recordings

### ISSUE THREAD

**Issue by vckelly** [rmotr-curriculum/post-your-question-questions#56]
Hello, 

I'm enrolled in the Web Dev track and I am having a hard time accessing the live classes and recordings. Specifically, I tried to join the live class this past Tuesday (8/28) and was not able to. The button to join was greyed out...I am not sure what the issue might be. I also don't see a recording of the first Django class...will there be recordings of these classes available like in the past?

Best,

Connor

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by santiagobasulto** [comment]
Hey Connor! I'll reach out over email now.
