### ISSUE TITLE
for loop statement

### ISSUE THREAD

**Issue by victorbizpetrol** [rmotr-curriculum/post-your-question-questions#58]
I have seen this for loop statement used a few times at rmotr,
but I have not been able to figure out how to use it or where
the syntax instructions are.  I have included the two examples I 
seen so far.

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
'''
I have seen this for loop statement used a few times at rmotr,
but I have not been able to figure out how to use it or where
the syntax instructions are.  I have included the two examples I 
seen so far.
'''


#EXample 1 
def invert_dict(a_dict):
    return {value: key for key, value in a_dict.items()}
    

#Example 2: from hangman/main.py 
def build_list_of_words(words, default_list):
    if words:
        return [w.strip() for w in words.split(',')]
    return default_list
```

**Comment by santiagobasulto** [comment]
Hello Victor! That's actually a list comprehension, that will be covered in Unit 8. We try to put a comment every time we use some piece of code from a more advanced unit, we've clearly forgotten here. I'll put those. Our idea is to show them early so they make a little bit more sense later, but always with a word of caution.

We'll also talk a lot about these when using Numpy and pandas with vectorized operations.

**Comment by victorbizpetrol** [comment]
Thanks!


Victor Castillo
310-210-4571
[p-logo-light-uppercase]
