### ISSUE TITLE
Football dictionaries project for week 3 - Travis Error

### ISSUE THREAD

**Issue by jjk235** [rmotr-curriculum/post-your-question-questions#59]
I'm getting an error through Travis even though my code works fine in c9. The error message is included in the code section. What can I do to fix this?

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
==================================== ERRORS ====================================
__________________________ ERROR collecting tests.py ___________________________
ImportError while importing test module '/home/travis/build/rmotr-group-projects/itp-u3-c2-football-dictionaries/tests.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests.py:7: in <module>
    from football_dictionaries.assignment_2 import players_by_position
football_dictionaries/assignment_2.py:1: in <module>
    from squads_data import SQUADS_DATA
E   ModuleNotFoundError: No module named 'squads_data'
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.16 seconds ============================
```

**Comment by santiagobasulto** [comment]
Hello @jjk235 ! How are you running those tests, with the command provided?

**Comment by gpriya** [comment]
How was this resolved?

**Comment by jjk235** [comment]
Hi guys. Sorry about the late reply - I got in touch with Jason so I thought I'd get help there instead. Basically the test was failing because the data and my code were in the same folder while the test file was outside of the directory so my way of importing without the period between the data and the code was failing because the test file was outside of the directory....? or something like that. Jason wasn't sure either so I'm hoping I'll just close the book on this for now?
