### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by qodetinker** [rmotr-curriculum/post-your-question-questions#6]
Can someone help me with getting set up with slack please?

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python

```

**Comment by martinzugnoni** [comment]
Hi there! Sure, I can send you an invite via email. Please let me know which email address you want to use.

**Comment by santiagobasulto** [comment]
@pq1 please email us at questions@rmotr.com with your email address.
