### ISSUE TITLE
while or for loop ?

### ISSUE THREAD

**Issue by mikoumed** [rmotr-curriculum/post-your-question-questions#62]
i just finished unit 1 exercices,
in one video it said that it is better to use for loops than while loops.
but in some exercices i found that is better for me to use while loops especially when I have to use character's position.
is there any trick to know what is better to use ?

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by marlontabone** [comment]
For loops and while loops have different purposes. Specifically, a while loop takes a condition and outputs according to the answer of that condition (a question). On the otherhand a for loop executes the code within it's brackets and asks no questions. A for loop will execute so many times according to what is specified in the arguments passed.
