### ISSUE TITLE
Palindromic Assignment

### ISSUE THREAD

**Issue by garybutler288** [rmotr-curriculum/post-your-question-questions#63]
This code returns True/False correctly on pythontutor.com but when I run the test on rmotr site it errors.  

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code herdef reverse_str(s):
    return s[::-1]

def is_palindromic(n):
    if reverse_str(n) == n:
        return True
    elif reverse_str(n)!= n:
        return False

print(is_palindromic('121'))
print(is_palindromic('CBC'))
print(is_palindromic('10201'))
print(is_palindromic('BOSS'))e (if any)

```

**Comment by jsymons** [comment]
You pasted your code into a comment.
```python
# your code herdef reverse_str(s):
    return s[::-1]
```
Should be
```python
def reverse_str(s):
    return s[::-1]
```

**Comment by garybutler288** [comment]
Must have happened when I copied it over.  I don't have e it in the comment
on the site.  It fails the test on rmotr.com but they all pass on
pythontutor.com.  Any suggestions
