### ISSUE TITLE
Using import between modules.

### ISSUE THREAD

**Issue by gpriya** [rmotr-curriculum/post-your-question-questions#64]
I was going thru the lecture video Class 7 - Modules and Virtualenvs and trying to follow along with the project that was being explained. I just commented out the line in search.py module within the package gist_search from gist_search.utils import get_gists.  When I typed it myself and tried to run it .. I got this error message 
Traceback (most recent call last):
  File "/home/ubuntu/workspace/gist_search/search.py", line 1, in <module>
    from gist_search.utils import get_gists
ImportError: No module named gist_search.utils

What am I doing wrong here. I am getting this same error when I tried to use import for the football_dictionaries project assignment. I wanted to reuse a function I wrote in assingment_1.py in other assignment modules. 

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
from gist_search.utils import get_gists



def search_gists(username, description=None, file_name=None):
    if not description and not file_name:
        print("At least one search parameter must be specified")
        return

```

**Comment by santiagobasulto** [comment]
it is usually related to the path of the file, where the file is located. Try adding `PYTHONPATH=.` at the beginning.
