### ISSUE TITLE
difference between elif and if

### ISSUE THREAD

**Issue by mikoumed** [rmotr-curriculum/post-your-question-questions#65]
why don't use only ifs?
it is working both ways but why in your exemples you are using elifs

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
if user_answer == guess_answer:
    ######
elif abs(user_answer - guess_answer) == threshold:
    ######
    
    or only use
if user_answer == guess_answer:
    ######
if abs(user_answer - guess_answer) == threshold:
    ######
    

```

**Comment by jsymons** [comment]
When using only `if`s you are doing more calculations. We only want to check if they were within the threshold if they *didn't* guess the exact answer.

With the `elif`s it first checks if they got the exact answer, and only if they didn't does it check if they're within the threshold. Generally you want to avoid extra calculations if possible. If we were looking to check both if they had the right answer *and* if they were within the threshold it would make sense to not use `elif`.

Hope that clears things up, if you have further questions let me know.
