### ISSUE TITLE
need help with test

### ISSUE THREAD

**Issue by yadlapallis** [rmotr-curriculum/post-your-question-questions#7]
need help in functions

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
pirate_saying = 'arrr'
def convert_pirate_to_dog(pirate_saying):
     
   
    for left_symbol in (pirate_saying):
      index =0
      right_index = index+1
      rigth_symbol = 'oo'
      print("{}{}".format(left_symbol,rigth_symbol),end ='')
      index +=1
    pirate_saying = 'arrr'
def convert_pirate_to_dog(pirate_saying):
     
   
    for left_symbol in (pirate_saying):
      index =0
      right_index = index+1
      rigth_symbol = 'oo'
      print("{}{}".format(left_symbol,rigth_symbol),end ='')
      index +=1
    pirate_saying = 'arrr'
def convert_pirate_to_dog(pirate_saying):
     
   
    for left_symbol in (pirate_saying):
      index =0
      right_index = index+1
      rigth_symbol = 'oo'
      print("{}{}".format(left_symbol,rigth_symbol),end ='')
      index +=1
    pirate_saying = 'arrr'
def convert_pirate_to_dog(pirate_saying):
     
   
    for left_symbol in (pirate_saying):
      index =0
      right_index = index+1
      rigth_symbol = 'oo'
      print("{}{}".format(left_symbol,rigth_symbol),end ='')
      index +=1
    
```

**Comment by santiagobasulto** [comment]
What assignment are you trying to solve @yadlapallis ?

**Comment by yadlapallis** [comment]
Convert Pirate to Dog in class 2 assignment 2
second question

pirate_saying = 'arrr'

for left_symbol in (pirate_saying):
      index =0
      right_index = index+1
      rigth_symbol = 'oo'
      print("{}{}".format(left_symbol,rigth_symbol),end ='')
      index +=1
i got the solution but not able to use the function in the for loop
please help

**Comment by santiagobasulto** [comment]
You're printing inside your function, which makes it impossible to pass the test, remember that your functions should **return**, not print.

Now, about the solution, it think it's a little bit easier and you might getting confused as you already started it too complicated, so let me see if I can help you start over.

You need to add `'oo'` after each letter. So, if `pirate_saying` is (for example) `'ABC'`. You should end up with `'AooBooCoo'`.

In a for loop, that'd be something like:

```python
new_word = ''
for letter in pirate_saying:
    new_word += letter # First the letter
    new_word += 'oo'  # always oo after the letter
print(new_word)
```

**Comment by yadlapallis** [comment]
help me to use function in  a for loop  iam not able to break it
