### ISSUE TITLE
Struggling to get pandas working on c9

### ISSUE THREAD

**Issue by jjk235** [rmotr-curriculum/post-your-question-questions#73]
Hi guys. I've struggled with this problem for the past 3 hours and I've been googling and googling to find answers (well, at least the answers I can understand) to solve it but I'm completely stuck now.

After creating a new virtual env and trying the command: pip install pandas

I got this error:
"Command python setup.py egg_info failed with error code 1 in /home/ubuntu/.virtualenvs/test2/build/pandas
Storing debug log for failure in /home/ubuntu/.pip/pip.log"

I found out that I can address this by updating my setup tools with this command: pip install --upgrade setuptools

and Pandas would install... or so I thought.

I created a new file and tried to import pandas and I get this error:

Traceback (most recent call last):
  File "/home/ubuntu/workspace/test.py", line 1, in <module>
    import pandas as pd
ImportError: No module named pandas

I'm able to run the file through bash: python test.py, but I'm not able to run the file with the green play button.

Any help or advice would be greatly appreciated, thank you.

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by santiagobasulto** [comment]
Hello @jjk235! Pandas build might fail in c9 because of Linux dependencies. Try with our notebooks instead https://notebooks.rmotr.com

**Comment by jjk235** [comment]
mmkay Thanks Santiago
