### ISSUE TITLE
Python IDEs?

### ISSUE THREAD

**Issue by ColemanSWE** [rmotr-curriculum/post-your-question-questions#75]
I am currently using PyCharm for project work but I was wondering if anyone thinks there is something better-suited for this course or Python/Django web development in general? I am on a Windows machine. Thanks in advance. 

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python

```

**Comment by santiagobasulto** [comment]
PyCharm is great! Other options to consider are Atom or VS Code, but they're less of an "IDE" and more like a plain text editor. Post it in #general and you'll probably get more answers :)
