### ISSUE TITLE
help me with the code below

### ISSUE THREAD

**Issue by yadlapallis** [rmotr-curriculum/post-your-question-questions#8]
def max_char(a_string):
   result_find_maxchar = ''
  
   for index,max_lower in enumerate(a_string):
       max_lower_index = index+1
       result_find_maxchar =max(a_string)
       if len(a_string) ==0:
          return ''
       else:
           max_lower_index = index+1
           result_find_maxchar =max(a_string)
return result_find_maxchar

**Comment by jsymons** [comment]
I think you're overcomplicating things here. You need to decide if you're going to solve this using a loop or `max`, not both. Also please be sure to format your code properly when submitting questions as it makes it much easier to read (See the insert code button that looks like <>)
