### ISSUE TITLE
Projects not getting submitted

### ISSUE THREAD

**Issue by r3dfear** [rmotr-curriculum/post-your-question-questions#83]
I have finished the previous projects, pulled requests and passed the travis test however on my profile dashboard it is not being shown as done

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by santiagobasulto** [comment]
Hello @r3dfear ! Can you tell me which ones? I'll look it up in our system

**Comment by r3dfear** [comment]
https://github.com/r3dfear/itp-u4-c2-hangman-game
https://github.com/r3dfear/itp-u3-c2-football-dictionaries
These two ones
