### ISSUE TITLE
format board help request

### ISSUE THREAD

**Issue by bulldg87** [rmotr-curriculum/post-your-question-questions#87]
Can someone walk through the format board question on how to resolve? 

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by santiagobasulto** [comment]
Hey @bulldg87! Here's the solution:

```python
BOARD_TEMPLATE = """
{0}  |  {1}  |  {2}
--------------
{3}  |  {4}  |  {5}
--------------
{6}  |  {7}  |  {8}
"""


def format_tic_tac_toe_board(first_row, second_row, third_row):
    return BOARD_TEMPLATE.format(
        first_row[0], first_row[1], first_row[2],
        second_row[0], second_row[1], second_row[2],
        third_row[0], third_row[1], third_row[2],
    )
```

The difficult part of this assignment is understanding that Strings in python can span multiple lines (with `"""` triple quotes). Each one of the `{1}` that you see in the template corresponds with a play that's filled later with `.format`.

Maybe you can bring it up in class to have the input from the instructor and others?

**Comment by bulldg87** [comment]
Yea I tried inputting the solution but it does not pass the test and
submits as "failed".

I think in general I just need to keep going through the homework with a
tutor one on one until it all clicks.
