### ISSUE TITLE
Could not turn a json file into dataframe

### ISSUE THREAD

**Issue by aler785** [rmotr-curriculum/post-your-question-questions#88]
Hi there, I am trying to do an exercise at home. It is a json file parsing directly in Pandas and do not understand how to complete it. Can you please help me?

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
#  your code here (if any)
#  Json structure
# {
#       "result": {
#         "60": [
#           [1481634360, 782.14, 782.14, 781.13, 781.13, 1.92525],
#           [1481634420, 782.02, 782.06, 781.94, 781.98, 2.37578],
#           [1481634480, 781.39, 781.94, 781.15, 781.94, 1.68882],
#           ...
#         ],
#         "180": [...],
#         "300": [...],
#         ...
#         "604800": [...]
#       }
#     }

#  pandas df structure desidered:
# | 60 | 1481634360 | 782.14 | 782.14 | 781.13 | 781.13 | 1.92525 |
# | 60 | 1481634420 | 782.02 | 782.06 | 781.94 | 781.98 | 2.37578 |
# ...
# | 180| ...
# 

  
```

**Comment by santiagobasulto** [comment]
Hey @aler785! It's not always as straightforward to go from dictionary to DataFrame. I say **dictionary** because that's no longer json, you've already parsed it as a dict.

Check the `pd.DataFrame.from_dict` method, it has an `orient` attribute that can be tuned.

**Comment by santiagobasulto** [comment]
Also, for this particular example, you could try with a MultiIndex if it make sense.
