### ISSUE TITLE
problems with  git_hub

### ISSUE THREAD

**Issue by yadlapallis** [rmotr-curriculum/post-your-question-questions#9]
not able to see rmotr_curiculum on cloud9  for advanced _collections please help

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by martinzugnoni** [comment]
Hello Ajay! Why are you trying to see the content in Github? Isn't it available in your dashboard? Please share any link that you are trying to use to access so I can help you.

**Comment by yadlapallis** [comment]
https://c9.io/rmotr

this is the link iam accesssing iam new to cloud9 got a new project to work
on from the class on monday

if you can call me or i can share the screen to show

**Comment by Jbforfun18** [comment]
I am trying to unsubscribe from git hub

**Comment by Jbforfun18** [comment]
Delete my acct
