### ISSUE TITLE
Case insensitive?

### ISSUE THREAD

**Issue by bbookman** [rmotr-curriculum/post-your-question-questions#92]
I noticed that the 'key' in the http header for your notebook example starts with an upper case character.  Yet in my code for the project, I look for ['location'] rather than ['Location'].  Seems I should get a key error if the key is really 'Location'.

What is really going on here?  does the .headers command include case insensitivity? 

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)

def perform_redirect_request():
    """Perform a request to a redirect URL and return the Location header that come in the response"""
    # HINT: you should use the allow_redirects parameter while doing the request
    url = 'https://httpbin.org/redirect/1'
    response = requests.get(url, allow_redirects = False)
    return response.headers['location']
    

""" In your notebook, you have this example response """

Access-Control-Allow-Credentials': 'true',
 'Access-Control-Allow-Origin': '*',
 'Connection': 'keep-alive',
 'Content-Length': '0',
 'Content-Type': 'text/html; charset=utf-8',
 'Date': 'Wed, 18 Apr 2018 21:12:51 GMT',
 'Location': 'https://google.com',
 'Server': 'meinheld/0.6.1',
 'Via': '1.1 vegur',
 'X-Powered-By': 'Flask',
 'X-Processed-Time': '0'}
```

**Comment by santiagobasulto** [comment]
Good question Bruce. HTTP Headers are case insensitive, and libraries usually respect that: https://tools.ietf.org/html/rfc7230#section-3.2
