### ISSUE TITLE
b-29_football_dictionaries_warmup

### ISSUE THREAD

**Issue by JaizWaheed** [rmotr-curriculum/post-your-question-questions#93]
I just started the football dictionaries project and I would like to know where do I put my code for the warmup activities?  I see assignment_1.py, assignment_2.py, and assignment_3.py,  in the football dictionaries folder for the main project, but what .py file do I use for the warmup?  Please let me know.  Thanks.   

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by santiagobasulto** [comment]
Hey @JaizWaheed! The warm up activities are "personal", they will not be tested. You can keep your solutions in the notebook.

**Comment by JaizWaheed** [comment]
Thanks
