### ISSUE TITLE
HTTP Assignment Test_7 Param Issue

### ISSUE THREAD

**Issue by bulldg87** [rmotr-curriculum/post-your-question-questions#96]
This is part of the http assignment. Test_7 continues to fail. I am not sure if I am labeling the param's wrong or if I'm missing something in the "resp" 

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
def perform_redirect_request():
    """Perform a request to a redirect URL and return the Location header that come in the response"""
    # HINT: you should use the allow_redirects parameter while doing the request
    url = 'https://httpbin.org/redirect/1'
    resp = requests.get(
        'https://httpbin.org/redirect-to', params = {
            'url': '/get',
        }, allow_redirects=False)
    resp
    resp.headers
    return resp
    
# This is part of the http assignment. Test_7 continues to fail
```

**Comment by jsymons** [comment]
You're just returning the response object here. The test is asking that you return the location header. So you need to access the headers from the response and return the location one.
