### ISSUE TITLE
'int' object is not subscriptable

### ISSUE THREAD

**Issue by Vuntsova** [rmotr-curriculum/post-your-question-questions#99]
What is the solution here

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
def reverse_str(s):
    return s[::-1]
    
print(reverse_str(56))
"""   
it gives me TypeError: 'int' object is not subscriptable.

I tryed also : return int(s)[::-1] and return int(s[::-1])
"""
```

**Comment by Vuntsova** [comment]
I think I got it:  return str(s)[::-1]?

**Comment by santiagobasulto** [comment]
Yes! You must first transform an "integer type" into a "string type" doing `str(s)`. And then you can reverse it. Great solution!
